name: mysteria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  badges: ^3.1.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  lottie: ^3.1.3
  meta: ^1.15.0
  pretty_dio_logger: ^1.4.0
  proj4dart: ^2.1.0
  provider: ^6.1.2
  retrofit: ^4.4.1
  timer_count_down: ^2.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.3
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/animation/
